lane :tests do
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    ignore_exit_status: true
  )
  run_tests(project: "gamebook.xcodeproj",
            devices: ["iPhone 11 Pro"],
            scheme: "gamebook",
	          clean: true,
	          code_coverage: true,
            skip_build: true)
  slather(scheme: "gamebook",
          proj: "./gamebook.xcodeproj",
          output_directory: "test_output/code_coverage/.", 
          cobertura_xml: true,
          html: true,
          coveralls: true,
          ignore: ["Pods/*", "ThirdParty/*", “Frameworks/*"])
end