lane :tests do
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    ignore_exit_status: true
  )
  run_tests(project: "gamebook.xcodeproj",
            devices: ["iPhone 11 Pro"],
            scheme: "gamebook",
	          clean: false,
	          code_coverage: true,
            skip_build: false)
end